Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Recebe um valor e devolve seu antecessor
// Autor(a)    : Evandro Jesus Da Silva
// Data atual  : 30/08/2026
Var
// Seção de Declarações das variáveis 
numero01:inteiro
antecessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Programa Antecessor")
Escreva("insira um número para saber seu antecessor : ")
Leia(numero01)
antecessor<-numero01-1
Escreva("O antecessor de ", numero01, " é : ", antecessor)
Fimalgoritmo