Algoritmo "AreaRetangulo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Recebe base e altura e devolve area do retangulo
// Autor(a)    : Evandro Jesus Da Silva
// Data atual  : 30/08/2026
Var
// Seção de Declarações das variáveis
base:inteiro
altura:inteiro
area:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Programa Calculador de area")
Escreva("Insira o valor da base do retangulo : ")
Leia(base)
Escreva("Insira o valor da altura do retangrulo : ")
Leia(altura)
area<-base*altura
Escreva("A area do retangulo equivale a : " ,area)

Fimalgoritmo