Algoritmo "Exercicio15"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler um valor e escrever a mensagem É MAIOR QUE
// 10! se o valor lido for maior que 10, caso contrário escrever
// NÃO É MAIOR QUE 10!
// Autor(a)    : Evandro Jesus Da Silva
// Data atual  : 31/08/2026
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um número :")
   Leia(numero)
   se numero>= 0 entao
      Escreval("É positivo !")
   senao
      Escreval("É negativo !")
   fimse

Fimalgoritmo